resources:
  - ../../base
patchesStrategicMerge:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller
    spec:
      template:
        spec:
          containers:
          - name: controller
            image: banviktor/image-clone-controller:main
            imagePullPolicy: IfNotPresent